### ISSUE TITLE
Unfork Project

### ISSUE THREAD

**Issue by faroit** [jrcurtis/subsequencely#1]
It probably makes sense to make this repo standalone rather than a fork. 
However to detach the fork and turn it into a standalone repository on GitHub, you need to contact GitHub support.

**Comment by jrcurtis** [comment]
Makes sense, but I'm not sure exactly how this works. Would I still be able to pull from the original repo when API updates get made? I also thought it was nice that people could find the project by clicking the forks button from the original.

**Comment by faroit** [comment]
github treats forks differently than the root repo when it comes to visibility in search etc. Also when you create branches etc github will notify you to send pull requests to the root repository which you are obviously not interested in.

You can locally add the original upstream repo as described [here](https://help.github.com/articles/configuring-a-remote-for-a-fork/). Then merging changes in the root repo is as easy as [this](https://help.github.com/articles/syncing-a-fork/)

**Comment by jrcurtis** [comment]
I put in the support request for this. I'll leave the issue open until it goes through.

**Comment by jrcurtis** [comment]
And that does it.
